# Generated by Django 4.1.5 on 2023-02-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clientAndServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('companyName', models.CharField(blank=True, max_length=50)),
                ('isClient', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='spendMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=30)),
                ('spendOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recivedMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=30)),
                ('recivedFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='paidUnpaidSalaryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlySalary', models.IntegerField()),
                ('month', models.DateField()),
                ('paidStatus', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
