# Generated by Django 4.1.5 on 2023-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_clientandserviceprovider_spendmoney_recivedmoney_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientandserviceprovider',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
