# Generated by Django 4.1.5 on 2023-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_clientandserviceprovider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientandserviceprovider',
            name='isClient',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
