# Generated by Django 4.1.5 on 2023-01-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_clientandserviceprovider_isclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deals',
        ),
    ]
