# Generated by Django 4.1.5 on 2023-02-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '__first__'),
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveOrReceive', models.CharField(choices=[('give', 'Give'), ('recive', 'Recive')], max_length=10)),
                ('dealAmount', models.IntegerField()),
                ('dealTitle', models.CharField(max_length=100)),
                ('dealDescription', models.TextField()),
                ('dealEnds', models.DateField()),
                ('dealWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider')),
                ('whoCanSee', models.ManyToManyField(to='userAuth.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='allDealsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveOrReceive', models.CharField(choices=[('give', 'Give'), ('recive', 'Recive')], max_length=10)),
                ('dealAmount', models.IntegerField()),
                ('dealTitle', models.CharField(max_length=100)),
                ('dealDescription', models.TextField()),
                ('dealEnds', models.DateField()),
                ('completeOrTerminated', models.CharField(choices=[('Completed', 'Completed'), ('Terminated', 'Terminated')], max_length=10)),
                ('dealWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider')),
            ],
        ),
    ]
