# Generated by Django 4.1.5 on 2023-01-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
        ('finance', '0010_delete_deals'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deals',
            new_name='currentDeals',
        ),
    ]
