# Generated by Django 4.1.5 on 2023-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_currentdeals_whocansee_currentdeals_whocansee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldealsrecord',
            name='dealDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currentdeals',
            name='dealDescription',
            field=models.TextField(blank=True),
        ),
    ]
