# Generated by Django 4.1.5 on 2023-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alldealsrecord_dealdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldealsrecord',
            name='dealTitle',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AddField(
            model_name='currentdeals',
            name='dealTitle',
            field=models.CharField(default='some', max_length=100),
        ),
        migrations.AlterField(
            model_name='alldealsrecord',
            name='dealDescription',
            field=models.TextField(default='some'),
        ),
        migrations.AlterField(
            model_name='currentdeals',
            name='dealDescription',
            field=models.TextField(default='some'),
        ),
    ]
