# Generated by Django 4.1.5 on 2023-01-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_delete_deals'),
        ('deals', '0006_alter_alldealsrecord_dealdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldealsrecord',
            name='dealWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider'),
        ),
        migrations.AlterField(
            model_name='currentdeals',
            name='dealWith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.clientandserviceprovider'),
        ),
    ]
