# Generated by Django 4.1.5 on 2023-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('needToComplete', models.BooleanField(default=False)),
                ('deadLine', models.DateField(blank=True, null=True)),
                ('completedBy', models.CharField(blank=True, max_length=10)),
                ('user', models.ManyToManyField(to='userAuth.userinfo')),
            ],
        ),
    ]
