# Generated by Django 4.1.5 on 2023-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='user',
            field=models.ManyToManyField(to='userAuth.userinfo'),
        ),
    ]
