# Generated by Django 4.1.5 on 2023-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='deadLine',
            field=models.DateField(blank=True, null=True),
        ),
    ]
