# Generated by Django 4.1.5 on 2023-01-29 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.TextField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')])),
                ('role', models.TextField(choices=[('1', 'Chief'), ('2', 'Moderator'), ('3', 'Human Resource'), ('4', 'Finance'), ('5', 'Office Employee')], default='5')),
                ('proPic', models.ImageField(blank=True, upload_to='propic')),
                ('fbLink', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
